USE [master]
GO

/****** Object:  Database [xmlParser]    Script Date: 4/28/2021 6:25:24 PM ******/
CREATE DATABASE [xmlParser]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'xmlParser', FILENAME = N'C:\Program Files (x86)\Plesk\Databases\MSSQL\MSSQL13.MSSQLSERVER2016\MSSQL\DATA\xmlParser.mdf' , SIZE = 8192KB , MAXSIZE = 3145728KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'xmlParser_log', FILENAME = N'C:\Program Files (x86)\Plesk\Databases\MSSQL\MSSQL13.MSSQLSERVER2016\MSSQL\DATA\xmlParser_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [xmlParser].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [xmlParser] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [xmlParser] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [xmlParser] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [xmlParser] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [xmlParser] SET ARITHABORT OFF 
GO

ALTER DATABASE [xmlParser] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [xmlParser] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [xmlParser] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [xmlParser] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [xmlParser] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [xmlParser] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [xmlParser] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [xmlParser] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [xmlParser] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [xmlParser] SET  ENABLE_BROKER 
GO

ALTER DATABASE [xmlParser] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [xmlParser] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [xmlParser] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [xmlParser] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [xmlParser] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [xmlParser] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [xmlParser] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [xmlParser] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [xmlParser] SET  MULTI_USER 
GO

ALTER DATABASE [xmlParser] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [xmlParser] SET DB_CHAINING OFF 
GO

ALTER DATABASE [xmlParser] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [xmlParser] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [xmlParser] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [xmlParser] SET QUERY_STORE = OFF
GO

USE [xmlParser]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [xmlParser] SET  READ_WRITE 
GO


