//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2020-21")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="ESFA/ILR/2020-21", IsNullable=false)]
public partial class Message {
    
    private MessageHeader headerField;
    
    private MessageSourceFiles sourceFilesField;
    
    private MessageLearningProvider learningProviderField;
    
    private MessageLearner[] learnerField;
    
    private MessageLearnerDestinationandProgression[] learnerDestinationandProgressionField;
    
    /// <remarks/>
    public MessageHeader Header {
        get {
            return this.headerField;
        }
        set {
            this.headerField = value;
        }
    }
    
    /// <remarks/>
    public MessageSourceFiles SourceFiles {
        get {
            return this.sourceFilesField;
        }
        set {
            this.sourceFilesField = value;
        }
    }
    
    /// <remarks/>
    public MessageLearningProvider LearningProvider {
        get {
            return this.learningProviderField;
        }
        set {
            this.learningProviderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Learner")]
    public MessageLearner[] Learner {
        get {
            return this.learnerField;
        }
        set {
            this.learnerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LearnerDestinationandProgression")]
    public MessageLearnerDestinationandProgression[] LearnerDestinationandProgression {
        get {
            return this.learnerDestinationandProgressionField;
        }
        set {
            this.learnerDestinationandProgressionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2020-21")]
public partial class MessageHeader {
    
    private MessageHeaderCollectionDetails collectionDetailsField;
    
    private MessageHeaderSource sourceField;
    
    /// <remarks/>
    public MessageHeaderCollectionDetails CollectionDetails {
        get {
            return this.collectionDetailsField;
        }
        set {
            this.collectionDetailsField = value;
        }
    }
    
    /// <remarks/>
    public MessageHeaderSource Source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2020-21")]
public partial class MessageHeaderCollectionDetails {
    
    private string collectionField;
    
    private ushort yearField;
    
    private System.DateTime filePreparationDateField;
    
    /// <remarks/>
    public string Collection {
        get {
            return this.collectionField;
        }
        set {
            this.collectionField = value;
        }
    }
    
    /// <remarks/>
    public ushort Year {
        get {
            return this.yearField;
        }
        set {
            this.yearField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime FilePreparationDate {
        get {
            return this.filePreparationDateField;
        }
        set {
            this.filePreparationDateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2020-21")]
public partial class MessageHeaderSource {
    
    private string protectiveMarkingField;
    
    private uint uKPRNField;
    
    private string softwareSupplierField;
    
    private string softwarePackageField;
    
    private byte releaseField;
    
    private byte serialNoField;
    
    private System.DateTime dateTimeField;
    
    private string referenceDataField;
    
    private byte componentSetVersionField;
    
    /// <remarks/>
    public string ProtectiveMarking {
        get {
            return this.protectiveMarkingField;
        }
        set {
            this.protectiveMarkingField = value;
        }
    }
    
    /// <remarks/>
    public uint UKPRN {
        get {
            return this.uKPRNField;
        }
        set {
            this.uKPRNField = value;
        }
    }
    
    /// <remarks/>
    public string SoftwareSupplier {
        get {
            return this.softwareSupplierField;
        }
        set {
            this.softwareSupplierField = value;
        }
    }
    
    /// <remarks/>
    public string SoftwarePackage {
        get {
            return this.softwarePackageField;
        }
        set {
            this.softwarePackageField = value;
        }
    }
    
    /// <remarks/>
    public byte Release {
        get {
            return this.releaseField;
        }
        set {
            this.releaseField = value;
        }
    }
    
    /// <remarks/>
    public byte SerialNo {
        get {
            return this.serialNoField;
        }
        set {
            this.serialNoField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime DateTime {
        get {
            return this.dateTimeField;
        }
        set {
            this.dateTimeField = value;
        }
    }
    
    /// <remarks/>
    public string ReferenceData {
        get {
            return this.referenceDataField;
        }
        set {
            this.referenceDataField = value;
        }
    }
    
    /// <remarks/>
    public byte ComponentSetVersion {
        get {
            return this.componentSetVersionField;
        }
        set {
            this.componentSetVersionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2020-21")]
public partial class MessageSourceFiles {
    
    private MessageSourceFilesSourceFile sourceFileField;
    
    /// <remarks/>
    public MessageSourceFilesSourceFile SourceFile {
        get {
            return this.sourceFileField;
        }
        set {
            this.sourceFileField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2020-21")]
public partial class MessageSourceFilesSourceFile {
    
    private string sourceFileNameField;
    
    private System.DateTime filePreparationDateField;
    
    private string softwareSupplierField;
    
    private string softwarePackageField;
    
    private byte releaseField;
    
    private byte serialNoField;
    
    private System.DateTime dateTimeField;
    
    /// <remarks/>
    public string SourceFileName {
        get {
            return this.sourceFileNameField;
        }
        set {
            this.sourceFileNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime FilePreparationDate {
        get {
            return this.filePreparationDateField;
        }
        set {
            this.filePreparationDateField = value;
        }
    }
    
    /// <remarks/>
    public string SoftwareSupplier {
        get {
            return this.softwareSupplierField;
        }
        set {
            this.softwareSupplierField = value;
        }
    }
    
    /// <remarks/>
    public string SoftwarePackage {
        get {
            return this.softwarePackageField;
        }
        set {
            this.softwarePackageField = value;
        }
    }
    
    /// <remarks/>
    public byte Release {
        get {
            return this.releaseField;
        }
        set {
            this.releaseField = value;
        }
    }
    
    /// <remarks/>
    public byte SerialNo {
        get {
            return this.serialNoField;
        }
        set {
            this.serialNoField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime DateTime {
        get {
            return this.dateTimeField;
        }
        set {
            this.dateTimeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2020-21")]
public partial class MessageLearningProvider {
    
    private uint uKPRNField;
    
    /// <remarks/>
    public uint UKPRN {
        get {
            return this.uKPRNField;
        }
        set {
            this.uKPRNField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2020-21")]
public partial class MessageLearner {
    
    private object[] itemsField;
    
    private ItemsChoiceType[] itemsElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ALSCost", typeof(ushort))]
    [System.Xml.Serialization.XmlElementAttribute("Accom", typeof(byte))]
    [System.Xml.Serialization.XmlElementAttribute("AddLine1", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("AddLine2", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("AddLine3", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("CampId", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("ContactPreference", typeof(MessageLearnerContactPreference))]
    [System.Xml.Serialization.XmlElementAttribute("DateOfBirth", typeof(System.DateTime), DataType="date")]
    [System.Xml.Serialization.XmlElementAttribute("Email", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("EngGrade", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Ethnicity", typeof(byte))]
    [System.Xml.Serialization.XmlElementAttribute("FamilyName", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("GivenNames", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("LLDDHealthProb", typeof(byte))]
    [System.Xml.Serialization.XmlElementAttribute("LLDDandHealthProblem", typeof(MessageLearnerLLDDandHealthProblem))]
    [System.Xml.Serialization.XmlElementAttribute("LearnRefNumber", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("LearnerEmploymentStatus", typeof(MessageLearnerLearnerEmploymentStatus))]
    [System.Xml.Serialization.XmlElementAttribute("LearnerFAM", typeof(MessageLearnerLearnerFAM))]
    [System.Xml.Serialization.XmlElementAttribute("LearnerHE", typeof(MessageLearnerLearnerHE))]
    [System.Xml.Serialization.XmlElementAttribute("LearningDelivery", typeof(MessageLearnerLearningDelivery))]
    [System.Xml.Serialization.XmlElementAttribute("MathGrade", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("NINumber", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("PMUKPRN", typeof(uint))]
    [System.Xml.Serialization.XmlElementAttribute("PlanEEPHours", typeof(byte))]
    [System.Xml.Serialization.XmlElementAttribute("PlanLearnHours", typeof(ushort))]
    [System.Xml.Serialization.XmlElementAttribute("Postcode", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("PostcodePrior", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("PrevLearnRefNumber", typeof(uint))]
    [System.Xml.Serialization.XmlElementAttribute("PriorAttain", typeof(byte))]
    [System.Xml.Serialization.XmlElementAttribute("ProviderSpecLearnerMonitoring", typeof(MessageLearnerProviderSpecLearnerMonitoring))]
    [System.Xml.Serialization.XmlElementAttribute("Sex", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("TelNo", typeof(uint))]
    [System.Xml.Serialization.XmlElementAttribute("ULN", typeof(ulong))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2020-21")]
public partial class MessageLearnerContactPreference {
    
    private string contPrefTypeField;
    
    private byte contPrefCodeField;
    
    /// <remarks/>
    public string ContPrefType {
        get {
            return this.contPrefTypeField;
        }
        set {
            this.contPrefTypeField = value;
        }
    }
    
    /// <remarks/>
    public byte ContPrefCode {
        get {
            return this.contPrefCodeField;
        }
        set {
            this.contPrefCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2020-21")]
public partial class MessageLearnerLLDDandHealthProblem {
    
    private byte lLDDCatField;
    
    private byte primaryLLDDField;
    
    private bool primaryLLDDFieldSpecified;
    
    /// <remarks/>
    public byte LLDDCat {
        get {
            return this.lLDDCatField;
        }
        set {
            this.lLDDCatField = value;
        }
    }
    
    /// <remarks/>
    public byte PrimaryLLDD {
        get {
            return this.primaryLLDDField;
        }
        set {
            this.primaryLLDDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PrimaryLLDDSpecified {
        get {
            return this.primaryLLDDFieldSpecified;
        }
        set {
            this.primaryLLDDFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2020-21")]
public partial class MessageLearnerLearnerEmploymentStatus {
    
    private byte empStatField;
    
    private System.DateTime dateEmpStatAppField;
    
    private uint empIdField;
    
    private bool empIdFieldSpecified;
    
    private MessageLearnerLearnerEmploymentStatusEmploymentStatusMonitoring[] employmentStatusMonitoringField;
    
    /// <remarks/>
    public byte EmpStat {
        get {
            return this.empStatField;
        }
        set {
            this.empStatField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime DateEmpStatApp {
        get {
            return this.dateEmpStatAppField;
        }
        set {
            this.dateEmpStatAppField = value;
        }
    }
    
    /// <remarks/>
    public uint EmpId {
        get {
            return this.empIdField;
        }
        set {
            this.empIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EmpIdSpecified {
        get {
            return this.empIdFieldSpecified;
        }
        set {
            this.empIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("EmploymentStatusMonitoring")]
    public MessageLearnerLearnerEmploymentStatusEmploymentStatusMonitoring[] EmploymentStatusMonitoring {
        get {
            return this.employmentStatusMonitoringField;
        }
        set {
            this.employmentStatusMonitoringField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2020-21")]
public partial class MessageLearnerLearnerEmploymentStatusEmploymentStatusMonitoring {
    
    private string eSMTypeField;
    
    private byte eSMCodeField;
    
    /// <remarks/>
    public string ESMType {
        get {
            return this.eSMTypeField;
        }
        set {
            this.eSMTypeField = value;
        }
    }
    
    /// <remarks/>
    public byte ESMCode {
        get {
            return this.eSMCodeField;
        }
        set {
            this.eSMCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2020-21")]
public partial class MessageLearnerLearnerFAM {
    
    private string learnFAMTypeField;
    
    private byte learnFAMCodeField;
    
    /// <remarks/>
    public string LearnFAMType {
        get {
            return this.learnFAMTypeField;
        }
        set {
            this.learnFAMTypeField = value;
        }
    }
    
    /// <remarks/>
    public byte LearnFAMCode {
        get {
            return this.learnFAMCodeField;
        }
        set {
            this.learnFAMCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2020-21")]
public partial class MessageLearnerLearnerHE {
    
    private uint uCASPERIDField;
    
    private byte tTACCOMField;
    
    private MessageLearnerLearnerHELearnerHEFinancialSupport learnerHEFinancialSupportField;
    
    /// <remarks/>
    public uint UCASPERID {
        get {
            return this.uCASPERIDField;
        }
        set {
            this.uCASPERIDField = value;
        }
    }
    
    /// <remarks/>
    public byte TTACCOM {
        get {
            return this.tTACCOMField;
        }
        set {
            this.tTACCOMField = value;
        }
    }
    
    /// <remarks/>
    public MessageLearnerLearnerHELearnerHEFinancialSupport LearnerHEFinancialSupport {
        get {
            return this.learnerHEFinancialSupportField;
        }
        set {
            this.learnerHEFinancialSupportField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2020-21")]
public partial class MessageLearnerLearnerHELearnerHEFinancialSupport {
    
    private byte fINTYPEField;
    
    private ushort fINAMOUNTField;
    
    /// <remarks/>
    public byte FINTYPE {
        get {
            return this.fINTYPEField;
        }
        set {
            this.fINTYPEField = value;
        }
    }
    
    /// <remarks/>
    public ushort FINAMOUNT {
        get {
            return this.fINAMOUNTField;
        }
        set {
            this.fINAMOUNTField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2020-21")]
public partial class MessageLearnerLearningDelivery {
    
    private string learnAimRefField;
    
    private byte aimTypeField;
    
    private byte aimSeqNumberField;
    
    private System.DateTime learnStartDateField;
    
    private System.DateTime origLearnStartDateField;
    
    private bool origLearnStartDateFieldSpecified;
    
    private System.DateTime learnPlanEndDateField;
    
    private byte fundModelField;
    
    private ushort pHoursField;
    
    private bool pHoursFieldSpecified;
    
    private byte progTypeField;
    
    private bool progTypeFieldSpecified;
    
    private byte stdCodeField;
    
    private bool stdCodeFieldSpecified;
    
    private ushort fworkCodeField;
    
    private bool fworkCodeFieldSpecified;
    
    private byte pwayCodeField;
    
    private bool pwayCodeFieldSpecified;
    
    private string delLocPostCodeField;
    
    private string ePAOrgIDField;
    
    private byte priorLearnFundAdjField;
    
    private bool priorLearnFundAdjFieldSpecified;
    
    private string conRefNumberField;
    
    private string lSDPostcodeField;
    
    private byte compStatusField;
    
    private System.DateTime learnActEndDateField;
    
    private bool learnActEndDateFieldSpecified;
    
    private byte withdrawReasonField;
    
    private bool withdrawReasonFieldSpecified;
    
    private byte outcomeField;
    
    private bool outcomeFieldSpecified;
    
    private string outGradeField;
    
    private System.DateTime achDateField;
    
    private bool achDateFieldSpecified;
    
    private string sWSupAimIdField;
    
    private MessageLearnerLearningDeliveryLearningDeliveryFAM[] learningDeliveryFAMField;
    
    private MessageLearnerLearningDeliveryProviderSpecDeliveryMonitoring[] providerSpecDeliveryMonitoringField;
    
    private MessageLearnerLearningDeliveryLearningDeliveryHE learningDeliveryHEField;
    
    private MessageLearnerLearningDeliveryAppFinRecord[] appFinRecordField;
    
    private MessageLearnerLearningDeliveryLearningDeliveryWorkPlacement learningDeliveryWorkPlacementField;
    
    /// <remarks/>
    public string LearnAimRef {
        get {
            return this.learnAimRefField;
        }
        set {
            this.learnAimRefField = value;
        }
    }
    
    /// <remarks/>
    public byte AimType {
        get {
            return this.aimTypeField;
        }
        set {
            this.aimTypeField = value;
        }
    }
    
    /// <remarks/>
    public byte AimSeqNumber {
        get {
            return this.aimSeqNumberField;
        }
        set {
            this.aimSeqNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime LearnStartDate {
        get {
            return this.learnStartDateField;
        }
        set {
            this.learnStartDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime OrigLearnStartDate {
        get {
            return this.origLearnStartDateField;
        }
        set {
            this.origLearnStartDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OrigLearnStartDateSpecified {
        get {
            return this.origLearnStartDateFieldSpecified;
        }
        set {
            this.origLearnStartDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime LearnPlanEndDate {
        get {
            return this.learnPlanEndDateField;
        }
        set {
            this.learnPlanEndDateField = value;
        }
    }
    
    /// <remarks/>
    public byte FundModel {
        get {
            return this.fundModelField;
        }
        set {
            this.fundModelField = value;
        }
    }
    
    /// <remarks/>
    public ushort PHours {
        get {
            return this.pHoursField;
        }
        set {
            this.pHoursField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PHoursSpecified {
        get {
            return this.pHoursFieldSpecified;
        }
        set {
            this.pHoursFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte ProgType {
        get {
            return this.progTypeField;
        }
        set {
            this.progTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ProgTypeSpecified {
        get {
            return this.progTypeFieldSpecified;
        }
        set {
            this.progTypeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte StdCode {
        get {
            return this.stdCodeField;
        }
        set {
            this.stdCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StdCodeSpecified {
        get {
            return this.stdCodeFieldSpecified;
        }
        set {
            this.stdCodeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public ushort FworkCode {
        get {
            return this.fworkCodeField;
        }
        set {
            this.fworkCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FworkCodeSpecified {
        get {
            return this.fworkCodeFieldSpecified;
        }
        set {
            this.fworkCodeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte PwayCode {
        get {
            return this.pwayCodeField;
        }
        set {
            this.pwayCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PwayCodeSpecified {
        get {
            return this.pwayCodeFieldSpecified;
        }
        set {
            this.pwayCodeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string DelLocPostCode {
        get {
            return this.delLocPostCodeField;
        }
        set {
            this.delLocPostCodeField = value;
        }
    }
    
    /// <remarks/>
    public string EPAOrgID {
        get {
            return this.ePAOrgIDField;
        }
        set {
            this.ePAOrgIDField = value;
        }
    }
    
    /// <remarks/>
    public byte PriorLearnFundAdj {
        get {
            return this.priorLearnFundAdjField;
        }
        set {
            this.priorLearnFundAdjField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PriorLearnFundAdjSpecified {
        get {
            return this.priorLearnFundAdjFieldSpecified;
        }
        set {
            this.priorLearnFundAdjFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string ConRefNumber {
        get {
            return this.conRefNumberField;
        }
        set {
            this.conRefNumberField = value;
        }
    }
    
    /// <remarks/>
    public string LSDPostcode {
        get {
            return this.lSDPostcodeField;
        }
        set {
            this.lSDPostcodeField = value;
        }
    }
    
    /// <remarks/>
    public byte CompStatus {
        get {
            return this.compStatusField;
        }
        set {
            this.compStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime LearnActEndDate {
        get {
            return this.learnActEndDateField;
        }
        set {
            this.learnActEndDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LearnActEndDateSpecified {
        get {
            return this.learnActEndDateFieldSpecified;
        }
        set {
            this.learnActEndDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte WithdrawReason {
        get {
            return this.withdrawReasonField;
        }
        set {
            this.withdrawReasonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool WithdrawReasonSpecified {
        get {
            return this.withdrawReasonFieldSpecified;
        }
        set {
            this.withdrawReasonFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte Outcome {
        get {
            return this.outcomeField;
        }
        set {
            this.outcomeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OutcomeSpecified {
        get {
            return this.outcomeFieldSpecified;
        }
        set {
            this.outcomeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string OutGrade {
        get {
            return this.outGradeField;
        }
        set {
            this.outGradeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime AchDate {
        get {
            return this.achDateField;
        }
        set {
            this.achDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AchDateSpecified {
        get {
            return this.achDateFieldSpecified;
        }
        set {
            this.achDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string SWSupAimId {
        get {
            return this.sWSupAimIdField;
        }
        set {
            this.sWSupAimIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LearningDeliveryFAM")]
    public MessageLearnerLearningDeliveryLearningDeliveryFAM[] LearningDeliveryFAM {
        get {
            return this.learningDeliveryFAMField;
        }
        set {
            this.learningDeliveryFAMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ProviderSpecDeliveryMonitoring")]
    public MessageLearnerLearningDeliveryProviderSpecDeliveryMonitoring[] ProviderSpecDeliveryMonitoring {
        get {
            return this.providerSpecDeliveryMonitoringField;
        }
        set {
            this.providerSpecDeliveryMonitoringField = value;
        }
    }
    
    /// <remarks/>
    public MessageLearnerLearningDeliveryLearningDeliveryHE LearningDeliveryHE {
        get {
            return this.learningDeliveryHEField;
        }
        set {
            this.learningDeliveryHEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AppFinRecord")]
    public MessageLearnerLearningDeliveryAppFinRecord[] AppFinRecord {
        get {
            return this.appFinRecordField;
        }
        set {
            this.appFinRecordField = value;
        }
    }
    
    /// <remarks/>
    public MessageLearnerLearningDeliveryLearningDeliveryWorkPlacement LearningDeliveryWorkPlacement {
        get {
            return this.learningDeliveryWorkPlacementField;
        }
        set {
            this.learningDeliveryWorkPlacementField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2020-21")]
public partial class MessageLearnerLearningDeliveryLearningDeliveryFAM {
    
    private string learnDelFAMTypeField;
    
    private ushort learnDelFAMCodeField;
    
    private System.DateTime learnDelFAMDateFromField;
    
    private bool learnDelFAMDateFromFieldSpecified;
    
    private System.DateTime learnDelFAMDateToField;
    
    private bool learnDelFAMDateToFieldSpecified;
    
    /// <remarks/>
    public string LearnDelFAMType {
        get {
            return this.learnDelFAMTypeField;
        }
        set {
            this.learnDelFAMTypeField = value;
        }
    }
    
    /// <remarks/>
    public ushort LearnDelFAMCode {
        get {
            return this.learnDelFAMCodeField;
        }
        set {
            this.learnDelFAMCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime LearnDelFAMDateFrom {
        get {
            return this.learnDelFAMDateFromField;
        }
        set {
            this.learnDelFAMDateFromField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LearnDelFAMDateFromSpecified {
        get {
            return this.learnDelFAMDateFromFieldSpecified;
        }
        set {
            this.learnDelFAMDateFromFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime LearnDelFAMDateTo {
        get {
            return this.learnDelFAMDateToField;
        }
        set {
            this.learnDelFAMDateToField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LearnDelFAMDateToSpecified {
        get {
            return this.learnDelFAMDateToFieldSpecified;
        }
        set {
            this.learnDelFAMDateToFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2020-21")]
public partial class MessageLearnerLearningDeliveryProviderSpecDeliveryMonitoring {
    
    private string provSpecDelMonOccurField;
    
    private string provSpecDelMonField;
    
    /// <remarks/>
    public string ProvSpecDelMonOccur {
        get {
            return this.provSpecDelMonOccurField;
        }
        set {
            this.provSpecDelMonOccurField = value;
        }
    }
    
    /// <remarks/>
    public string ProvSpecDelMon {
        get {
            return this.provSpecDelMonField;
        }
        set {
            this.provSpecDelMonField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2020-21")]
public partial class MessageLearnerLearningDeliveryLearningDeliveryHE {
    
    private ushort nUMHUSField;
    
    private string sSNField;
    
    private string qUALENT3Field;
    
    private byte sOC2000Field;
    
    private byte sECField;
    
    private byte uCASAPPIDField;
    
    private byte tYPEYRField;
    
    private byte mODESTUDField;
    
    private byte fUNDLEVField;
    
    private byte fUNDCOMPField;
    
    private byte sTULOADField;
    
    private byte yEARSTUField;
    
    private byte mSTUFEEField;
    
    private byte pCFLDCSField;
    
    private byte sPECFEEField;
    
    private byte nETFEEField;
    
    private ushort gROSSFEEField;
    
    private string dOMICILEField;
    
    private byte eLQField;
    
    private string hEPostCodeField;
    
    /// <remarks/>
    public ushort NUMHUS {
        get {
            return this.nUMHUSField;
        }
        set {
            this.nUMHUSField = value;
        }
    }
    
    /// <remarks/>
    public string SSN {
        get {
            return this.sSNField;
        }
        set {
            this.sSNField = value;
        }
    }
    
    /// <remarks/>
    public string QUALENT3 {
        get {
            return this.qUALENT3Field;
        }
        set {
            this.qUALENT3Field = value;
        }
    }
    
    /// <remarks/>
    public byte SOC2000 {
        get {
            return this.sOC2000Field;
        }
        set {
            this.sOC2000Field = value;
        }
    }
    
    /// <remarks/>
    public byte SEC {
        get {
            return this.sECField;
        }
        set {
            this.sECField = value;
        }
    }
    
    /// <remarks/>
    public byte UCASAPPID {
        get {
            return this.uCASAPPIDField;
        }
        set {
            this.uCASAPPIDField = value;
        }
    }
    
    /// <remarks/>
    public byte TYPEYR {
        get {
            return this.tYPEYRField;
        }
        set {
            this.tYPEYRField = value;
        }
    }
    
    /// <remarks/>
    public byte MODESTUD {
        get {
            return this.mODESTUDField;
        }
        set {
            this.mODESTUDField = value;
        }
    }
    
    /// <remarks/>
    public byte FUNDLEV {
        get {
            return this.fUNDLEVField;
        }
        set {
            this.fUNDLEVField = value;
        }
    }
    
    /// <remarks/>
    public byte FUNDCOMP {
        get {
            return this.fUNDCOMPField;
        }
        set {
            this.fUNDCOMPField = value;
        }
    }
    
    /// <remarks/>
    public byte STULOAD {
        get {
            return this.sTULOADField;
        }
        set {
            this.sTULOADField = value;
        }
    }
    
    /// <remarks/>
    public byte YEARSTU {
        get {
            return this.yEARSTUField;
        }
        set {
            this.yEARSTUField = value;
        }
    }
    
    /// <remarks/>
    public byte MSTUFEE {
        get {
            return this.mSTUFEEField;
        }
        set {
            this.mSTUFEEField = value;
        }
    }
    
    /// <remarks/>
    public byte PCFLDCS {
        get {
            return this.pCFLDCSField;
        }
        set {
            this.pCFLDCSField = value;
        }
    }
    
    /// <remarks/>
    public byte SPECFEE {
        get {
            return this.sPECFEEField;
        }
        set {
            this.sPECFEEField = value;
        }
    }
    
    /// <remarks/>
    public byte NETFEE {
        get {
            return this.nETFEEField;
        }
        set {
            this.nETFEEField = value;
        }
    }
    
    /// <remarks/>
    public ushort GROSSFEE {
        get {
            return this.gROSSFEEField;
        }
        set {
            this.gROSSFEEField = value;
        }
    }
    
    /// <remarks/>
    public string DOMICILE {
        get {
            return this.dOMICILEField;
        }
        set {
            this.dOMICILEField = value;
        }
    }
    
    /// <remarks/>
    public byte ELQ {
        get {
            return this.eLQField;
        }
        set {
            this.eLQField = value;
        }
    }
    
    /// <remarks/>
    public string HEPostCode {
        get {
            return this.hEPostCodeField;
        }
        set {
            this.hEPostCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2020-21")]
public partial class MessageLearnerLearningDeliveryAppFinRecord {
    
    private string aFinTypeField;
    
    private byte aFinCodeField;
    
    private System.DateTime aFinDateField;
    
    private ushort aFinAmountField;
    
    /// <remarks/>
    public string AFinType {
        get {
            return this.aFinTypeField;
        }
        set {
            this.aFinTypeField = value;
        }
    }
    
    /// <remarks/>
    public byte AFinCode {
        get {
            return this.aFinCodeField;
        }
        set {
            this.aFinCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime AFinDate {
        get {
            return this.aFinDateField;
        }
        set {
            this.aFinDateField = value;
        }
    }
    
    /// <remarks/>
    public ushort AFinAmount {
        get {
            return this.aFinAmountField;
        }
        set {
            this.aFinAmountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2020-21")]
public partial class MessageLearnerLearningDeliveryLearningDeliveryWorkPlacement {
    
    private System.DateTime workPlaceStartDateField;
    
    private System.DateTime workPlaceEndDateField;
    
    private bool workPlaceEndDateFieldSpecified;
    
    private ushort workPlaceHoursField;
    
    private byte workPlaceModeField;
    
    private uint workPlaceEmpIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime WorkPlaceStartDate {
        get {
            return this.workPlaceStartDateField;
        }
        set {
            this.workPlaceStartDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime WorkPlaceEndDate {
        get {
            return this.workPlaceEndDateField;
        }
        set {
            this.workPlaceEndDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool WorkPlaceEndDateSpecified {
        get {
            return this.workPlaceEndDateFieldSpecified;
        }
        set {
            this.workPlaceEndDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public ushort WorkPlaceHours {
        get {
            return this.workPlaceHoursField;
        }
        set {
            this.workPlaceHoursField = value;
        }
    }
    
    /// <remarks/>
    public byte WorkPlaceMode {
        get {
            return this.workPlaceModeField;
        }
        set {
            this.workPlaceModeField = value;
        }
    }
    
    /// <remarks/>
    public uint WorkPlaceEmpId {
        get {
            return this.workPlaceEmpIdField;
        }
        set {
            this.workPlaceEmpIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2020-21")]
public partial class MessageLearnerProviderSpecLearnerMonitoring {
    
    private string provSpecLearnMonOccurField;
    
    private string provSpecLearnMonField;
    
    /// <remarks/>
    public string ProvSpecLearnMonOccur {
        get {
            return this.provSpecLearnMonOccurField;
        }
        set {
            this.provSpecLearnMonOccurField = value;
        }
    }
    
    /// <remarks/>
    public string ProvSpecLearnMon {
        get {
            return this.provSpecLearnMonField;
        }
        set {
            this.provSpecLearnMonField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="ESFA/ILR/2020-21", IncludeInSchema=false)]
public enum ItemsChoiceType {
    
    /// <remarks/>
    ALSCost,
    
    /// <remarks/>
    Accom,
    
    /// <remarks/>
    AddLine1,
    
    /// <remarks/>
    AddLine2,
    
    /// <remarks/>
    AddLine3,
    
    /// <remarks/>
    CampId,
    
    /// <remarks/>
    ContactPreference,
    
    /// <remarks/>
    DateOfBirth,
    
    /// <remarks/>
    Email,
    
    /// <remarks/>
    EngGrade,
    
    /// <remarks/>
    Ethnicity,
    
    /// <remarks/>
    FamilyName,
    
    /// <remarks/>
    GivenNames,
    
    /// <remarks/>
    LLDDHealthProb,
    
    /// <remarks/>
    LLDDandHealthProblem,
    
    /// <remarks/>
    LearnRefNumber,
    
    /// <remarks/>
    LearnerEmploymentStatus,
    
    /// <remarks/>
    LearnerFAM,
    
    /// <remarks/>
    LearnerHE,
    
    /// <remarks/>
    LearningDelivery,
    
    /// <remarks/>
    MathGrade,
    
    /// <remarks/>
    NINumber,
    
    /// <remarks/>
    PMUKPRN,
    
    /// <remarks/>
    PlanEEPHours,
    
    /// <remarks/>
    PlanLearnHours,
    
    /// <remarks/>
    Postcode,
    
    /// <remarks/>
    PostcodePrior,
    
    /// <remarks/>
    PrevLearnRefNumber,
    
    /// <remarks/>
    PriorAttain,
    
    /// <remarks/>
    ProviderSpecLearnerMonitoring,
    
    /// <remarks/>
    Sex,
    
    /// <remarks/>
    TelNo,
    
    /// <remarks/>
    ULN,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2020-21")]
public partial class MessageLearnerDestinationandProgression {
    
    private string learnRefNumberField;
    
    private ulong uLNField;
    
    private MessageLearnerDestinationandProgressionDPOutcome[] dPOutcomeField;
    
    /// <remarks/>
    public string LearnRefNumber {
        get {
            return this.learnRefNumberField;
        }
        set {
            this.learnRefNumberField = value;
        }
    }
    
    /// <remarks/>
    public ulong ULN {
        get {
            return this.uLNField;
        }
        set {
            this.uLNField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DPOutcome")]
    public MessageLearnerDestinationandProgressionDPOutcome[] DPOutcome {
        get {
            return this.dPOutcomeField;
        }
        set {
            this.dPOutcomeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2020-21")]
public partial class MessageLearnerDestinationandProgressionDPOutcome {
    
    private string outTypeField;
    
    private byte outCodeField;
    
    private System.DateTime outStartDateField;
    
    private System.DateTime outCollDateField;
    
    /// <remarks/>
    public string OutType {
        get {
            return this.outTypeField;
        }
        set {
            this.outTypeField = value;
        }
    }
    
    /// <remarks/>
    public byte OutCode {
        get {
            return this.outCodeField;
        }
        set {
            this.outCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime OutStartDate {
        get {
            return this.outStartDateField;
        }
        set {
            this.outStartDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime OutCollDate {
        get {
            return this.outCollDateField;
        }
        set {
            this.outCollDateField = value;
        }
    }
}
